import { Poppins } from "next/font/google";
import Header from "../components/shared/header";
import "./globals.css";
import { Footer } from "@/components/shared/footer";
import Script from "next/script";

const geistPoppins = Poppins({
  variable: "--font-Poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "photoАтелье",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={geistPoppins.className}>
        <main className="min-h-screen relative overflow-hidden text-[#fff] bg-[#131313]">
          <Header />
          {children}
          <Footer />

          <Script
            src="https://api-maps.yandex.ru/2.1/?apikey=d01bc6d6-6f64-4d8e-949e-09787ec37356&lang=ru_RU"
            strategy="beforeInteractive"
          />
        </main>
      </body>
    </html>
  );
}
